rm -f ../log/load*.log
rm -f ../log/mart*.log
rm -f ../log/select*.log
rm -f ../log/tpcds*.log

./run_load.01.sh &
./run_load.02.sh &
./run_load.03.sh &
./run_load.04.sh &
./run_load.05.sh &
./run_load.06.sh &
./run_load.07.sh &
./run_load.08.sh &
./run_load.09.sh &
./run_load.10.sh &
./run_load.11.sh &
./run_load.12.sh &
./run_load.13.sh &
./run_load.14.sh &
./run_load.15.sh &
#./run_load.16.sh &
#./run_load.17.sh &
#./run_load.18.sh &
#./run_load.19.sh &
#./run_load.20.sh &
#./run_load.21.sh &
#./run_load.22.sh &
#./run_load.23.sh &
#./run_load.24.sh &
#./run_load.31.sh &
#./run_load.32.sh &
#./run_load.33.sh &
#./run_load.34.sh &
#./run_load.35.sh &
#./run_load.36.sh &
./run_mart.01.sh &
./run_mart.02.sh &
./run_mart.03.sh &
./run_mart.04.sh &
./run_mart.05.sh &
./run_mart.06.sh &
./run_select.01.sh &
./run_select.02.sh &
./run_select.03.sh &
./run_select.04.sh &
./run_select.05.sh &
./run_select.06.sh &
./run_select.07.sh &
./run_select.08.sh &

./run_tpcds.01.sh &
#./run_tpcds.02.sh &
#./run_tpcds.03.sh &
#./run_tpcds.04.sh &
./run_tpcds.05.sh &
./run_tpcds.06.sh &
./run_tpcds.07.sh &
./run_tpcds.08.sh &
./run_tpcds.09.sh &
./run_tpcds.10.sh &
./run_tpcds.11.sh &
./run_tpcds.12.sh &
./run_tpcds.13.sh &
#./run_tpcds.14.sh &
./run_tpcds.15.sh &
./run_tpcds.16.sh &
./run_tpcds.17.sh &
./run_tpcds.18.sh &
./run_tpcds.19.sh &
./run_tpcds.20.sh &
./run_tpcds.21.sh &
./run_tpcds.22.sh &
#./run_tpcds.23.sh &
#./run_tpcds.24.sh &
./run_tpcds.25.sh &
./run_tpcds.26.sh &
./run_tpcds.27.sh &
./run_tpcds.28.sh &
./run_tpcds.29.sh &
./run_tpcds.30.sh &
./run_tpcds.31.sh &
./run_tpcds.32.sh &
./run_tpcds.33.sh &
./run_tpcds.34.sh &
./run_tpcds.35.sh &
./run_tpcds.36.sh &
./run_tpcds.37.sh &
./run_tpcds.38.sh &
./run_tpcds.39.sh &
./run_tpcds.40.sh &
./run_tpcds.41.sh &
./run_tpcds.42.sh &
./run_tpcds.43.sh &
./run_tpcds.44.sh &
#./run_tpcds.45.sh &
#./run_tpcds.46.sh &
#./run_tpcds.47.sh &
#./run_tpcds.48.sh &
#./run_tpcds.49.sh &
#./run_tpcds.50.sh &
#./run_tpcds.51.sh &
#./run_tpcds.52.sh &
#./run_tpcds.53.sh &
#./run_tpcds.54.sh &
#./run_tpcds.55.sh &
#./run_tpcds.56.sh &
#./run_tpcds.57.sh &
#./run_tpcds.58.sh &
#./run_tpcds.59.sh &
#./run_tpcds.60.sh &
#./run_tpcds.61.sh &
#./run_tpcds.62.sh &
#./run_tpcds.63.sh &
#./run_tpcds.64.sh &
#./run_tpcds.65.sh &
#./run_tpcds.66.sh &
#./run_tpcds.67.sh &
#./run_tpcds.68.sh &
#./run_tpcds.69.sh &
#./run_tpcds.70.sh &
#./run_tpcds.71.sh &
#./run_tpcds.72.sh &
#./run_tpcds.73.sh &
#./run_tpcds.74.sh &
#./run_tpcds.75.sh &
#./run_tpcds.76.sh &
#./run_tpcds.77.sh &
#./run_tpcds.78.sh &
#./run_tpcds.79.sh &
#./run_tpcds.80.sh &
#./run_tpcds.81.sh &
#./run_tpcds.82.sh &
#./run_tpcds.83.sh &
#./run_tpcds.84.sh &
#./run_tpcds.85.sh &
#./run_tpcds.86.sh &
#./run_tpcds.87.sh &
#./run_tpcds.88.sh &
#./run_tpcds.89.sh &
#./run_tpcds.90.sh &
#./run_tpcds.91.sh &
#./run_tpcds.92.sh &
#./run_tpcds.93.sh &
#./run_tpcds.94.sh &
#./run_tpcds.95.sh &
#./run_tpcds.96.sh &
#./run_tpcds.97.sh &
#./run_tpcds.98.sh &
#./run_tpcds.99.sh &
